// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: geo.sql

package repository

import (
	"context"
)

const addPoint = `-- name: AddPoint :one
INSERT INTO points (title, point) -- lon/lat (X/Y)
VALUES ($1, st_setsrid(st_makepoint($2::float8, $3::float8), 4326))
RETURNING id
`

type AddPointParams struct {
	Name string  `json:"name"`
	Lon  float64 `json:"lon"`
	Lat  float64 `json:"lat"`
}

func (q *Queries) AddPoint(ctx context.Context, arg AddPointParams) (int32, error) {
	row := q.db.QueryRow(ctx, addPoint, arg.Name, arg.Lon, arg.Lat)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getPointsFromBox = `-- name: GetPointsFromBox :many
SELECT id, title AS name, st_x(point)::float8 AS lon, st_y(point)::float8 AS lat
FROM points
WHERE point && st_makeenvelope($1::float8, $2::float8, $3::float8, $4::float8, 4326)
`

type GetPointsFromBoxParams struct {
	Lon1 float64 `json:"lon1"`
	Lat1 float64 `json:"lat1"`
	Lon2 float64 `json:"lon2"`
	Lat2 float64 `json:"lat2"`
}

type GetPointsFromBoxRow struct {
	ID   int32   `json:"id"`
	Name string  `json:"name"`
	Lon  float64 `json:"lon"`
	Lat  float64 `json:"lat"`
}

func (q *Queries) GetPointsFromBox(ctx context.Context, arg GetPointsFromBoxParams) ([]GetPointsFromBoxRow, error) {
	rows, err := q.db.Query(ctx, getPointsFromBox,
		arg.Lon1,
		arg.Lat1,
		arg.Lon2,
		arg.Lat2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPointsFromBoxRow{}
	for rows.Next() {
		var i GetPointsFromBoxRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Lon,
			&i.Lat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
